apiVersion: v1
kind: Pod
metadata:
  name: jekyll
  namespace: development
  labels:
    run: jekyll
spec:
  initContainers:
    - name: copy-jekyll
      image: kodekloud/jekyll
      command: ["jekyll", "new", "site"]
  containers:
  - name: jekyll
    image: gcr.io/kodekloud/customimage/jekyll-serv:latest
    resources: {}
    volumeMounts:
      - mountPath: /site
        name: site
  volumes:
    - name: site
      persistentVolumeClaim:
        claimName: jekyll-site

