apiVersion: v1
kind: PersistentVolume
metadata:
  name: jekyll-pv
  namespace: development
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage

