apiVersion: v1
kind: Service
metadata:
  name: jekyll-node-service
  namespace: development
spec:
  selector:
    run: jekyll
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  type: NodePort
